name: Deploy Backend to Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Only run when backend files change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Get the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Login to AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1 

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 3. Build & Push (With the Fixes!)
    - name: Build and Push Docker Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mnist-repo
        IMAGE_TAG: latest
      run: |
        cd backend
        # We use --provenance=false to fix the Lambda error
        # We use --platform=linux/amd64 to ensure it works on AWS servers
        docker build --provenance=false --platform=linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # 4. Update Lambda
    - name: Update Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name mnist-func \
          --image-uri ${{ steps.login-ecr.outputs.registry }}/mnist-repo:latest